# Generated by Django 3.0.7 on 2020-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
        ('customers', '0002_auto_20200622_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='policies',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='policies.Policy'),
        ),
    ]
